CC = g++
CFLAGS = -std=c++0x -Wall

all: main.o main clean

main.o: 2ndTCMain.cpp
	$(CC) -c 2ndTCMain.cpp -o $@ $(CFLAGS)

main: main.o
	$(CC) -o $@ $^ $(CFLAGS)

.PHONY: clean exe
clean:
	rm main.o

exe:
	./main
	./main
	./main
	./main
	./main
	./main
	./main
	./main
	./main
	./main
	./main
	./main
	./main
	./main
	./main